services:
  fe-app:
    image: belshed/fe-app
    build: .
    hostname: fe-app
    environment:
      - MAP_URL=${MAP_URL}
    ports:
      - 81:3000
  nginx:
    image: belshed/fe-app-nginx
    build: ./nginx
    ports:
      - 80:80
    depends_on:
     - fe-app