name: Main Landing Action

on:
  push:
    branches: [ "master" ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v3
      with:
        path: ~/.npm
        restore-keys: |
          ${{ runner.os }}-
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install --no-scripts
    
  stylelint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm i stylelint
      - run: npm run stylelint
    
  eslint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm i eslint
      - run: npm run eslint
      
  build:
    runs-on: ubuntu-latest
    needs: [eslint, stylelint]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push to Docker
        uses: docker/build-push-action@v4.1.1
        with:
          pull: true
          push: true
      
