name: Main Landing Action

on:
  push:
    branches: [ "master" ]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Bulild Docker containers
        run: docker compose build --build-arg MAP_URL=${{ vars.MAP_URL }}
      
