name: Main Landing Action

on:
  push:
    branches: [ "master" ]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
      - uses: docker/login-action@v2.2.0
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Bulild Docker containers
        run: ls
      
